[package]
name = "aoce_advent_plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "aoce_advent_plugin"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19"
tl = "0.7"
log = "0.4"
